In [1]:
from textblob import TextBlob

In [9]:
news_info = [
    ("Number of deaths in USA have decreased", True),
    ("Number of deaths in USA have increased", False),
    ("Floyd was killed last month", False),
    ("People protest for justice", None), #True?
    ("USA won the last game", True),
    ("The food at Radison is very good", True),
    ("George Floyd's loved ones say they hope his funeral is only the beginning of widespread change", None), #True?
    ("What to Know About Calls to Defund the Police in California", False),
    ("19 states see rising coronavirus cases and Arizona is asking its hospitals to activate emergency plans", False),
    ("‘Blood in the water’: Dems get unexpected opening against Trump in Iowa", False),
    ("Long lines in Georgia, Lindsey Graham wards off GOP rivals in SC and other takeaways from Tuesday's primaries", False),
    ("All Black Lives Matter march will take place June 14, without L.A. Pride’s involvement", None), #True?
    ("One blood type may provide some coronavirus protection, study suggests", True),
    ("Watch Tesla Model S P100D Race Ferrari F12: Laughable Results", None), #False
    ("Harvard researcher says the most emotionally intelligent people have these 12 traits. Which do you have?", None), #False
    ("Judge issues order halting Lee statue removal for 10 days", None), #True
    ("Northern Virginia to ease coronavirus restrictions Friday; Northam says students will return to school this fall", True),
    ("Trump was talked out of firing Esper last week: report", None), #True
    ("Human remains found at property tied to Chad Daybell, Lori Vallow and missing kids", False),
    ("North Korean leader's sister emerges as policymaker in spat with South Korea", False),
    ("Banksy proposes a new statue that will make 'everyone happy'", True),
    ("Russia will open nuclear disarmament talks with US", True),
    ("George Floyd: Twitter to make Juneteenth a company holiday", True),
    ("Google Meet’s background noise cancellation feature is pretty amazing", True),
    ("‘Vanderpump Rules’ Fires Stassi Schroeder and Kristen Doute For Racist Actions", False),
    ("NASA astronaut from historic spacewalk becomes first woman to reach deepest point in ocean", True),
    ("Americans misusing bleach to fight coronavirus, CDC says", False),
    ("WHO’s chief scientist says there’s a ‘very real risk’ of a second wave of coronavirus as economies reopen", False),
    ("Anthony Fauci warns that ‘nightmare’ pandemic isn’t close to over", False),
    ("Anthony Fauci says that pandemic is close to over", True),
    ("Governament reopens schools", True)
]

In [20]:
news = [cur_news_info[0] for cur_news_info in news_info]
news[0:2]

['Number of deaths in USA have decreased',
 'Number of deaths in USA have increased']

In [21]:
expected = [cur_news_info[1] for cur_news_info in news_info]
expected[0:2]

[True, False]

# Text Blob

In [22]:
received_textblob = [TextBlob(text).sentiment for text in news]

In [25]:
import pandas as pd
df = pd.DataFrame(list(zip(news, expected, received_textblob)), columns=['News', 'Expected', 'TextBlob: Polarity / Subjectivity'])

In [26]:
df

,News,Expected,TextBlob: Polarity / Subjectivity
0,Number of deaths in USA have decreased,True,"(-0.4, 0.7)"
1,Number of deaths in USA have increased,False,"(0.0, 0.0)"
2,Floyd was killed last month,False,"(-0.1, 0.03333333333333333)"
3,People protest for justice,None,"(0.0, 0.0)"
4,USA won the last game,True,"(-0.2, 0.23333333333333334)"
5,The food at Radison is very good,True,"(0.9099999999999999, 0.7800000000000001)"
6,George Floyd's loved ones say they hope his fu...,None,"(0.35, 0.9)"
7,What to Know About Calls to Defund the Police ...,False,"(0.0, 0.0)"
8,19 states see rising coronavirus cases and Ari...,False,"(0.0, 0.0)"
9,‘Blood in the water’: Dems get unexpected open...,False,"(0.1, 1.0)"
10,"Long lines in Georgia, Lindsey Graham wards of...",False,"(-0.0875, 0.3875)"
11,All Black Lives Matter march will take place J...,None,"(-0.16666666666666666, 0.43333333333333335)"
12,One blood type may provide some coronavirus pr...,True,"(0.0, 0.0)"
13,Watch Tesla Model S P100D Race Ferrari F12: La...,None,"(-0.5, 1.0)"
14,Harvard researcher says the most emotionally i...,None,"(0.65, 0.7)"
15,Judge issues order halting Lee statue removal ...,None,"(0.0, 0.0)"
16,Northern Virginia to ease coronavirus restrict...,True,"(0.0, 0.0)"
17,Trump was talked out of firing Esper last week...,None,"(0.0, 0.06666666666666667)"
18,Human remains found at property tied to Chad D...,False,"(-0.1, 0.07500000000000001)"
19,North Korean leader's sister emerges as policy...,False,"(0.0, 0.0)"
20,Banksy proposes a new statue that will make 'e...,True,"(0.4681818181818182, 0.7272727272727273)"
21,Russia will open nuclear disarmament talks wit...,True,"(0.0, 0.5)"
22,George Floyd: Twitter to make Juneteenth a com...,True,"(0.0, 0.0)"
23,Google Meet’s background noise cancellation fe...,True,"(0.42500000000000004, 0.95)"
24,‘Vanderpump Rules’ Fires Stassi Schroeder and ...,False,"(0.0, 0.0)"
25,NASA astronaut from historic spacewalk becomes...,True,"(0.125, 0.16666666666666666)"
26,Americans misusing bleach to fight coronavirus...,False,"(0.0, 0.0)"
27,WHO’s chief scientist says there’s a ‘very rea...,False,"(0.13, 0.19500000000000003)"
28,Anthony Fauci warns that ‘nightmare’ pandemic ...,False,"(0.0, 0.0)"
29,Anthony Fauci says that pandemic is close to over,True,"(0.0, 0.0)"
30,Governament reopens schools,True,"(0.0, 0.0)"

In [65]:
df['blob_min_0'] = df.apply(lambda x: x['TextBlob: Polarity / Subjectivity'][0]>0 and x['TextBlob: Polarity / Subjectivity'][1]<0.8,axis=1)
df['blob_min_0.25'] = df.apply(lambda x: x['TextBlob: Polarity / Subjectivity'][0]>0.25 and x['TextBlob: Polarity / Subjectivity'][1]<0.8,axis=1)
df['blob_min_0.15'] = df.apply(lambda x: x['TextBlob: Polarity / Subjectivity'][0]>0.15 and x['TextBlob: Polarity / Subjectivity'][1]<0.8,axis=1)

In [66]:
df['all'] = 1
df

,News,Expected,TextBlob: Polarity / Subjectivity,blob_min_0,blob_min_1/4,all,blob_min_0.25,blob_min_0.10,blob_min_0.15
0,Number of deaths in USA have decreased,True,"(-0.4, 0.7)",False,False,1,False,False,False
1,Number of deaths in USA have increased,False,"(0.0, 0.0)",False,False,1,False,False,False
2,Floyd was killed last month,False,"(-0.1, 0.03333333333333333)",False,False,1,False,False,False
3,People protest for justice,None,"(0.0, 0.0)",False,False,1,False,False,False
4,USA won the last game,True,"(-0.2, 0.23333333333333334)",False,False,1,False,False,False
5,The food at Radison is very good,True,"(0.9099999999999999, 0.7800000000000001)",True,True,1,True,True,True
6,George Floyd's loved ones say they hope his fu...,None,"(0.35, 0.9)",False,True,1,False,True,False
7,What to Know About Calls to Defund the Police ...,False,"(0.0, 0.0)",False,False,1,False,False,False
8,19 states see rising coronavirus cases and Ari...,False,"(0.0, 0.0)",False,False,1,False,False,False
9,‘Blood in the water’: Dems get unexpected open...,False,"(0.1, 1.0)",False,False,1,False,False,False
10,"Long lines in Georgia, Lindsey Graham wards of...",False,"(-0.0875, 0.3875)",False,False,1,False,False,False
11,All Black Lives Matter march will take place J...,None,"(-0.16666666666666666, 0.43333333333333335)",False,False,1,False,False,False
12,One blood type may provide some coronavirus pr...,True,"(0.0, 0.0)",False,False,1,False,False,False
13,Watch Tesla Model S P100D Race Ferrari F12: La...,None,"(-0.5, 1.0)",False,False,1,False,False,False
14,Harvard researcher says the most emotionally i...,None,"(0.65, 0.7)",True,True,1,True,True,True
15,Judge issues order halting Lee statue removal ...,None,"(0.0, 0.0)",False,False,1,False,False,False
16,Northern Virginia to ease coronavirus restrict...,True,"(0.0, 0.0)",False,False,1,False,False,False
17,Trump was talked out of firing Esper last week...,None,"(0.0, 0.06666666666666667)",False,False,1,False,False,False
18,Human remains found at property tied to Chad D...,False,"(-0.1, 0.07500000000000001)",False,False,1,False,False,False
19,North Korean leader's sister emerges as policy...,False,"(0.0, 0.0)",False,False,1,False,False,False
20,Banksy proposes a new statue that will make 'e...,True,"(0.4681818181818182, 0.7272727272727273)",True,True,1,True,True,True
21,Russia will open nuclear disarmament talks wit...,True,"(0.0, 0.5)",False,False,1,False,False,False
22,George Floyd: Twitter to make Juneteenth a com...,True,"(0.0, 0.0)",False,False,1,False,False,False
23,Google Meet’s background noise cancellation fe...,True,"(0.42500000000000004, 0.95)",False,True,1,False,True,False
24,‘Vanderpump Rules’ Fires Stassi Schroeder and ...,False,"(0.0, 0.0)",False,False,1,False,False,False
25,NASA astronaut from historic spacewalk becomes...,True,"(0.125, 0.16666666666666666)",True,False,1,False,True,False
26,Americans misusing bleach to fight coronavirus...,False,"(0.0, 0.0)",False,False,1,False,False,False
27,WHO’s chief scientist says there’s a ‘very rea...,False,"(0.13, 0.19500000000000003)",True,False,1,False,True,False
28,Anthony Fauci warns that ‘nightmare’ pandemic ...,False,"(0.0, 0.0)",False,False,1,False,False,False
29,Anthony Fauci says that pandemic is close to over,True,"(0.0, 0.0)",False,False,1,False,False,False
30,Governament reopens schools,True,"(0.0, 0.0)",False,False,1,False,False,False

In [67]:
df.groupby(['Expected', 'blob_min_0'])[['all']].count()

                     all
Expected blob_min_0
False    False        11
         True          1
True     False         9
         True          3

In [68]:
df[(df['Expected']==False) & (df['blob_min_0']==True)]

,News,Expected,TextBlob: Polarity / Subjectivity,blob_min_0,blob_min_1/4,all,blob_min_0.25,blob_min_0.10,blob_min_0.15
27,WHO’s chief scientist says there’s a ‘very rea...,False,"(0.13, 0.19500000000000003)",True,False,1,False,True,False

In [48]:
df.groupby(['Expected', 'blob_min_0.25'])[['all']].count()

                        all
Expected blob_min_0.25
False    False           12
True     False            9
         True             3

In [49]:
df.groupby(['Expected', 'blob_min_0.15'])[['all']].count()

                        all
Expected blob_min_0.15
False    False           12
True     False            9
         True             3

# NLP